backend:
  name: github
  repo: mrYakamoto/gatsby-netlify-cms

media_folder: static/assets

collections:
  - name: blog
    label: Blog
    folder: _blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
