backend:
  name: github
  repo: mrYakamoto/gatsby-netlify-cms

media_folder: static/assets

collections:
  - name: articles
    label: Article
    folder: articles
    create: true
    fields:
      - {name: url, label: URL}
      - {name: title, label: Title}
      - {name: date, label: Date, widget: date}
      - {name: publication, label: Publication, widget: relation, collection: publications, searchFields: [name], valueField: name}
      # TODO: add image field

  - name: publications
    label: Publication
    folder: publications
    create: true
    fields:
      - {name: name, label: Name}
      - {name: url, label: URL}
      # TODO: add logo image field
