backend:
  name: github
  repo: mrYakamoto/gatsby-netlify-cms

media_folder: static/assets

# collections must have either a title or a path field
collections:
  - name: publication
    label: Publication
    folder: content/_publication
    create: true
    fields:
      - { name: title, label: Title }
      - { name: url, label: Url }
  - name: article
    label: Article
    folder: content/_article
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: publication, label: Publication, widget: relation, collection: publication, searchFields: [title], valueField: title }
      - { name: date, label: Date, widget: date }
