backend:
  name: github
  repo: mrYakamoto/gatsby-netlify-cms

media_folder: static/assets

# collections must have either a title or a path field
collections:
  - name: publication
    label: Publication
    folder: _publication
    create: true
    fields:
      - { name: title, label: Title }
      - { name: url, label: Url }
  - name: article
    label: Article
    folder: _article
    create: true
    fields:
      - { name: title, label: Title }
      - { name: publication, label: Publication, widget: relation, collection: authors, searchFields: [title], valueField: title }
