backend:
  name: github
  repo: mrYakamoto/gatsby-netlify-cms

media_folder: static/assets

collections:
  - name: article
    label: Article
    folder: article
    create: true
    fields:
      - {name: url, label: URL}
      - {name: title, label: Title}
      - {publication: publication, label: publication}
      - {name: date, label: Date}
